[package]
name = "rivulet-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rivulet-core = { path = "../rivulet-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
